ARG FRAPPE_PATH=https://github.com/frappe/frappe
ARG FRAPPE_BRANCH=version-15
ARG ERPNEXT_BRANCH=version-15
ARG PYTHON_VERSION=3.10.13
ARG NODE_VERSION=18.18.2
ARG APPS_JSON_BASE64

# Use the correct official base image shown in your Docker Hub screenshot
FROM frappe/erpnext:version-15

# The base image already includes Frappe + ERPNext.
# APPS_JSON_BASE64 is used by the build process to install additional apps (changAI)
